tap "homebrew/bundle"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Modern replacement for 'ls'
brew "exa"
# Simple, fast and user-friendly alternative to find
brew "fd"
# Command-line tools for fly.io services
brew "flyctl"
# Fast and simple Node.js version manager
brew "fnm"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# GNU implementation of the famous stream editor
brew "gnu-sed"
# Powerful, lightweight programming language
brew "lua"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# HTTP load generator, inspired by rakyll/hey with tui animation
brew "oha"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# SOcket CAT: netcat on steroids
brew "socat"
# Command-line client for WebSockets
brew "websocat"
# Command-line interface for 1Password
cask "1password-cli"
vscode "13xforever.language-x86-64-assembly"
vscode "adpyke.vscode-sql-formatter"
vscode "astro-build.astro-vscode"
vscode "bmalehorn.vscode-fish"
vscode "bradlc.vscode-tailwindcss"
vscode "cschlosser.doxdocgen"
vscode "csstools.postcss"
vscode "dan-c-underwood.arm"
vscode "DavidAnson.vscode-markdownlint"
vscode "dbaeumer.vscode-eslint"
vscode "denoland.vscode-deno"
vscode "dsznajder.es7-react-js-snippets"
vscode "eamodio.gitlens"
vscode "EditorConfig.EditorConfig"
vscode "esbenp.prettier-vscode"
vscode "formulahendry.auto-close-tag"
vscode "formulahendry.auto-rename-tag"
vscode "foxundermoon.shell-format"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "GitHub.remotehub"
vscode "GraphQL.vscode-graphql"
vscode "GraphQL.vscode-graphql-syntax"
vscode "hbenl.vscode-mocha-test-adapter"
vscode "hbenl.vscode-test-explorer"
vscode "jeff-hykin.better-cpp-syntax"
vscode "k--kato.intellij-idea-keybindings"
vscode "mattpocock.ts-error-translator"
vscode "mikestead.dotenv"
vscode "mohsen1.prettify-json"
vscode "ms-azuretools.vscode-docker"
vscode "ms-dotnettools.vscode-dotnet-runtime"
vscode "ms-mssql.data-workspace-vscode"
vscode "ms-mssql.mssql"
vscode "ms-mssql.sql-bindings-vscode"
vscode "ms-mssql.sql-database-projects-vscode"
vscode "ms-playwright.playwright"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode.cpptools-themes"
vscode "ms-vscode.remote-repositories"
vscode "ms-vscode.test-adapter-converter"
vscode "ms-vsliveshare.vsliveshare"
vscode "Prisma.prisma"
vscode "redhat.vscode-yaml"
vscode "ritwickdey.LiveServer"
vscode "steoates.autoimport"
vscode "streetsidesoftware.code-spell-checker"
vscode "stylelint.vscode-stylelint"
vscode "sumneko.lua"
vscode "svelte.svelte-vscode"
vscode "tobiasalthoff.atom-material-theme"
vscode "uctakeoff.vscode-counter"
vscode "vscode-icons-team.vscode-icons"
vscode "Vue.volar"
vscode "withfig.fig"
vscode "xsro.masm-tasm"
vscode "xsro.vscode-dosbox"
vscode "ZixuanChen.vitest-explorer"
